services:
  ### Vector DB (Qdrant)
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-vcell
    ports:
      - "6333:6333"     # REST API
      - "6334:6334"     # gRPC API
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

  ### Backend (FastAPI with Poetry)
  backend:
    build: ./backend
    container_name: vcell-backend
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./backend:/app 
    command: ["sh", "-c", "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    env_file:
      - ./backend/.env

  ### Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-vcell
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

volumes:
  qdrant-data:
    driver: local