---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: vcell-ai-rke-dev
spec:
  encryptedData:
    .dockerconfigjson: AgA2Dg7Umt6FZBIW+HKs1sl4iwdkpeyxK2gi8hpJ1p3Tkdx3pZZErj8X1XQ5Iat6kOY9DrfybVYir/NdQEvvB6P3PK1X9rfnDWyOUmOQnpwqG1owOvx5d0z25Ki3s1EKZ/HtQQhBr2z5jNHw8YkSFnLKEaYfrvIbgFr8UMwmLIg7fsCQJ7wOUgSZ92MtF+kkfkDuy2N0nCVvM0JLj6suyC2AzCpoaAIAtb/XjDyVfrJd/oaq6zZKetVRlYrNKI25iyyItQtdcDDOl5WafXivynDrIW8sFO6Y1ySep7glHq4HnOFFhFF1aGmtJgAw4tBzIhlK1bKEZHgYzQ44pwok+fg8AnMvggF5zhEpBDYXmKjbF1tDAVYhTIHpCQNf5QRQ0of/6QdmjYnBmwaGgqOFLRWPwC32+A4dzhkOdJeB6/inAANdy71AwaUs66WHliBZqRT0jAFV5nFQfBYqGillnQ3pDyiEVoAgAEW7inQxkElsUu++/vEinr7wtOEnPpc3+bIFTa1x62/hVD9ngx5BtwItZTlazQQND83bmgXAaiGztuOGCkTMSlSJPzfQDzJcYgDk31lOv9EXud8vare1stYi73iXAl4hR4HG3iabOQe/w4q4GGXmZTEtGrg9VDfl3dWKSUXc0v6DEjeUAh1KDHFJSmP5cuIyMnzDCa9LtABNFncM0mKKEiBt1oOxpytwS6SV5smVm7Drk2eR3BTh3Vt1WNrX8OaBXElUOA2PvpkpbnE2JeOd+nt0GpCXBhpkyM00Q0eFquE0uvHFGAlddxTf0zmNRyGrFqqAD0oNZ3dDnQjruNLO1Fpk065rZrA2Cd7YkdtIUcaewfxTcWT74L3bkXz17VVRDQhfc9Qov+mIj/3PniyXtoZ6waTEj/dUL+fyu6EPM0wAIQljmuLzDR70ce908djMGpaOokDJHGRCq4V9vGox28AN9RRZ7iyIG4JQrOPvsS+Z98u5ses5ieEA
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: vcell-ai-rke-dev
    type: kubernetes.io/dockerconfigjson
