---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: vcell-ai-rke-dev
spec:
  encryptedData:
    auth0-client-secret: AgBor/HKvPQme9LDnU81AT9c61S8yh3os+vSjSAGa8IYY6adfFLYiVK59MvpjUTanp3B+YONyD5g33i63QTjRCr3OFKXXtEu1uFKtBw3EdkpR8paCAn/St9VNtuvGkzmDtDPaXD33WpZURxPnzEgjMo9W4Wyi9qjjP7X0xct0/FQxo57LWQF55hs8OEd4hfrVBgA9s59xTNiY2MbkxmhvFs9ZMkJ0Sa9mbjzU3VWOwIvMJGjL7v0A3WiQ0LHI1MzS8pwWaUs4gMal5Tl0yXfOXG2A7ZhqRVFIcaWt+kKUmvyt4f3p3ftac80i8l6mfFgjObaIhTQus8RLV+RLssgA+Q9hldLZYaK60KeEyCYdwIX7GZ8uKUE44qgQhUl43nGUaDJMCRtwXmKMiUQPHyOZnt5lhrsIGAiHXEjGIUSMN36N1CLwIi77j2rzlDvwJk9AYwmNHWZ46WwKtW7eFBer0iWJ+/1c/hKGuu/rVVPWGpMfoYDDrBPeOJmr4g7WTOvwTU5wPJq3CMBCXlc4QNAfbFDQCZ3ewJlxZSPhya1qAM7sKo7u9LTd2mTuwrvO6I5CGKmlVkSx42sQhlSMTEjTJtb17UqzhFC2l+K2hU+v/Y1aCcTJItgoB0/gRZQQ35lSfbv81/iOqIG7DLxjf/0fTuYkwuJUDX9dohUmmVH11t2cXvw8UEm+Wl9fPvyFmGsUrsAI5fQIjOt8lrTD9GVt6LWvfwI2SxOZE/0DxNlPWDUuAnmsta2h8fS+uQqjE4aRy8YNjhJ0ovpqvVmUDmsY/Vw
    auth0-secret: AgBKlI/rpUaBDiG3EEB6FueEzu2bSum6kyRSvUovGnqSYwytB1hw4Chrm5CD8e8ARwrBaZuARlIbVLN6SEVLE2B537jy85BPsy1z1UhF47i2XRCdAonfgzb2ScONTdmD7bavOjeQ/WagUeaKE/Nm5aGz63nYpI+2QgU8gTSRcCDInDmXMSxLhi9RyMh7liHmCcDIVRMreoenyZshcnQIy5NsBdaAuF5OyifPWPR8h/AFiplI9ctvSSB/0wLmjfiOSlFE0nLr569LCtxueiIjphjX8ySdijWXX2XqZoUdEAgihRp71nPcYNb+DEILN7DHvEDq71PVdM/obOXA+ZuGGAY/3oNjJrm/em3A3aVpV6Fh/VKRmex+MrqKHuSpJp00ji8vGlrgPl0ZFeRpuyed4hnQlPaPTpZ+yYo8X9gBoLCBnc6OXQUYJpYtLdjoE3N/ofnBqz0xzfldvHnd1bffActfEt2hRvKCz8fYtjsBGReNLp6KEl0/WtwhXmZlHKkfj8lTRs/QIvtEQFWKzQbZELS5XsH32sGo6lbg7m288vgmGrarJ2f4BAGaPBDjvJZkbNhxBjyFBl8R4i3tQhxLiBv+AtvcE2dcyj0uNYZuSAUUGQkUvRuzyG2bSGqqxdkT4XTqlXen6sYcz4Cs8YfPFn9ki4nuz8wO5kXWV0l36tbVHJbjEypEQZqsXPnH8r4Dy1KCl5HsB2B/L24atoCFv/ENXF4wL1EONQ81hBpF2HXyHc8D+uY6X7I=
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: vcell-ai-rke-dev
